name: supafund_trader
author: valory
version: 0.1.0
description: A service that runs the Supafund Trader agent.
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint: {}
fingerprint_ignore_patterns: []
agent: valory/supafund_trader:0.1.0:bafybeid3tafofebprow3jjnj4wo5v3mkmbcwfwgow4natocihc6mzrgmqq
number_of_agents: 4
deployment: {}
---
public_id: valory/supafund_trader_abci:0.1.0
type: skill
models:
  params:
    args:
      openai_api_key: ${OPENAI_API_KEY:str}
      supabase_url: ${NEXT_PUBLIC_SUPABASE_URL:str}
      supabase_key: ${SUPABASE_SERVICE_ROLE_KEY:str}
      github_token: ${GITHUB_TOKEN:str:null}
      setup:
        all_participants: ${ALL_PARTICIPANTS:list:[]}
        safe_contract_address: ${SAFE_CONTRACT_ADDRESS:str:null}
        consensus_threshold: ${CONSENSUS_THRESHOLD:int:null}
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: valory/supafund_trader_abci:0.1.0
  host: ${str:localhost}
  port: ${int:26658}
  use_tendermint: ${bool:false}
---
public_id: valory/http_client:0.23.0
type: connection
config:
  target_skill_id: valory/supafund_trader_abci:0.1.0
